### ISSUE TITLE
very often not working in Vs2017

### ISSUE THREAD

**Issue by EmilAlipiev** [tom-englert/ResXResourceManager#143] opened 2018-06-24 12:46 UTC
Hi, 

this is an awesome tool. thank you first of all but very often happens to me that when I open it using VS2017, it shows an empty designer and only way to resolve the problem is to uninstall and resinstall the extension. Do you know what could be the problem?

**Comment by MichaOnGit** [comment] 2018-06-25 18:56
Hi, it really is an excellent tool, but unfortunately I have exactly the same problem.

**Comment by tom-englert** [comment] 2018-06-26 06:17
Can you attach the messages from the output window?
________________________________
Von: Michael Wenninger<mailto:notifications@github.com>
Gesendet: ‎25.‎06.‎2018 20:56
An: tom-englert/ResXResourceManager<mailto:ResXResourceManager@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [tom-englert/ResXResourceManager] very often not working in Vs2017 (#143)


Hi, it really is an excellent tool, but unfortunately I have exactly the same problem.

**Comment by tom-englert** [comment] 2018-06-28 14:56
@EmilAlipiev @MichaOnGit anyone out there?

**Comment by tom-englert** [comment] 2018-06-28 15:22
Also maybe you can find a solution here: https://github.com/tom-englert/ResXResourceManager/wiki/Fixing-errors

**Comment by gaunts** [comment] 2018-06-29 09:50
Hello, I have the same issue. Output:

```
Loaded assembly 'ResXManager.Infrastructure, Version=1.22.1131.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/userName/AppData/Local/Microsoft/VisualStudio/15.0_902d4d90/Extensions/qmoh1jst.bpp/ResXManager.Infrastructure.DLL.
Loaded assembly 'ResXManager.Model, Version=1.22.1131.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/userName/AppData/Local/Microsoft/VisualStudio/15.0_902d4d90/Extensions/qmoh1jst.bpp/ResXManager.Model.dll.
Loaded assembly 'ResXManager.Translators, Version=1.22.1131.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/userName/AppData/Local/Microsoft/VisualStudio/15.0_902d4d90/Extensions/qmoh1jst.bpp/ResXManager.Translators.dll.
Loaded assembly 'ResXManager.View, Version=1.22.1131.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/userName/AppData/Local/Microsoft/VisualStudio/15.0_902d4d90/Extensions/qmoh1jst.bpp/ResXManager.View.dll.
Loaded assembly 'ResXManager.VSIX, Version=1.22.1131.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/userName/AppData/Local/Microsoft/VisualStudio/15.0_902d4d90/Extensions/qmoh1jst.bpp/ResXManager.VSIX.dll.
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\userName\AppData\Local\Microsoft\VisualStudio\15.0_902d4d90\Extensions\qmoh1jst.bpp
Version: 1.22.1131.0
.NET Framework Version: 461808 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Switch.System.Windows.Baml2006.AppendLocalAssemblyVersionForSourceUri=False (https://github.com/Microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md#wpf)

```

**Comment by tom-englert** [comment] 2018-06-29 15:44
@gaunts this does not show any problems, can you post a screenshot that corresponds to that output?

**Comment by gaunts** [comment] 2018-06-29 15:54
![resxmanagerissue](https://user-images.githubusercontent.com/3473452/42102055-2c3ecc20-7bc5-11e8-8ed2-8258189dc9d7.PNG)

It was working correctly with the same project, before the last visual studio update.

**Comment by tom-englert** [comment] 2018-06-29 16:43
Did you try https://github.com/remcoros/DuplicateExtensionFinder to see if there are any duplicates?

**Comment by tom-englert** [comment] 2018-07-13 15:55
@EmilAlipiev @MichaOnGit @gaunts any new input on this?

**Comment by EmilAlipiev** [comment] 2018-07-14 20:01
It looks like for me it is not repeating any longer after latest VS2017 updates. I will give my feedback if it happens again. you can close it if others have no objection :)

**Comment by wokhan** [comment] 2018-07-15 12:21
Well, updating to the last VS version fixed it (at least for now).
FYI I was using 15.7.4
Anyway this extension looks very promising! I was using MS Multilingual App Toolkit but am not convinced with it, especially when you realize than the extension translation itself is really bad ;-)
Thanks again

**Comment by tom-englert** [comment] 2018-07-15 13:23
OK, so I close this for now

**Comment by gaunts** [comment] 2018-07-16 12:40
Sorry @tom-englert it totally got out of my mind! The new VS update did not fix it for me :(

**Comment by tom-englert** [comment] 2018-07-16 15:09
@gaunts can you try the latest build, I've added some additional error tracing: http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/

**Comment by bluegrams** [comment] 2018-07-18 08:47
Hi, I also still have this issue, updating the tool and VS didn't solve it (the output also doesn't show any problems). I couldn't really figure in which cases it shows a blank page. E.g. the window is shown correctly if I start VS, then open ResX Manager first and after that open my project.

**Comment by tom-englert** [comment] 2018-07-18 16:24
@bluegrams maybe you can play around to find a pattern to reproduce this.

**Comment by tom-englert** [comment] 2018-07-20 15:00
That might be a hint, I'll try to use an UWP project.

**Comment by tom-englert** [comment] 2018-07-21 13:29
@bluegrams can you try the latest version from http://vsixgallery.com/extension/43b35fe0-1f30-48de-887a-68256474202a/, I've added some log to see when and how the content gets loaded.

**Comment by tom-englert** [comment] 2018-07-22 12:12
@bluegrams I tried the scenarios you have described above, but could not reproduce it.

**Comment by bluegrams** [comment] 2018-07-22 22:37
@tom-englert Sorry, I currently don't have the possibility to test the new logging on the machine where the issue occurred, I'll do that in a few days.
But I made some further testing on another machine with a newly installed VS and actually also couldn't reproduce the issue there. So it may be caused by some misconfiguration.

For the moment, thanks a lot for your effort, I really like this tool.

**Comment by gaunts** [comment] 2018-07-23 07:53
@tom-englert It started working for no specific reason on 2 of my setups. I didn't have the opportunity to test on the third one. I installed the version with more logs and will keep you updated if it happens again. Same as bluegrams, I am working on UWP projects.

**Comment by gaunts** [comment] 2018-07-24 08:44
@tom-englert It just happened !

```
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\simon\AppData\Local\Microsoft\VisualStudio\15.0_902d4d90\Extensions\mqlq2qel.plx
Version: 1.23.1141.0
.NET Framework Version: 461808 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Switch.System.Windows.Baml2006.AppendLocalAssemblyVersionForSourceUri=False (https://github.com/Microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md#wpf)
Error: tomenglertde.ResXManager.Model.ImportException: Error parsing the data from clipboard: The data you're pasting isn't the same size as your selection.
   at tomenglertde.ResXManager.View.Visuals.ResourceViewModel.PasteRows(IList`1 table) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceViewModel.cs:line 393
   at tomenglertde.ResXManager.View.Visuals.ResourceViewModel.Paste(DataGrid dataGrid) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceViewModel.cs:line 360
   at TomsToolbox.Wpf.DelegateCommand`1.Execute(Object parameter)
   at TomsToolbox.Wpf.Converters.ConfirmedCommandConverter.CommandProxy.Execute(Object parameter)
```

**Comment by tom-englert** [comment] 2018-07-24 14:22
@gaunts according to the stack trace you clicked "Paste", and it showed the error message "Error parsing the data from clipboard: The data you're pasting isn't the same size as your selection."
But how could you click "Paste" if the window is empty?

**Comment by gaunts** [comment] 2018-07-24 15:02
I don't know that. I emptied my clipboard and it didn't fix it. The problem happens again but I don't get this output anymore.. Simply no output when opening the extension.

**Comment by tom-englert** [comment] 2018-07-24 15:12
@gaunts 
- can you try 1.23.1149 from the VsixGallery?
- have a look at the windows content with snoop (http://www.cplotts.com/2017/10/27/snoop-2-8-0-download/) to see if it's really empty or just collapsed?

**Comment by wokhan** [comment] 2018-07-27 06:13
Previous version started failing unexpectedly (with no specific exception logged), and the latest one (1.23.1149) from vsixgallery does the same (blank screen and no errors, resizing looks alright => Content loaded: 1116,8 - 412,8).

**Comment by tom-englert** [comment] 2018-07-27 13:05
@wokhan can you then please have a look at the content with snoop?

**Comment by wokhan** [comment] 2018-07-29 08:16
The ContentPresenter inside the VsixShellView component is empty, at least according to Snoop. ActualHeight is OK though so it looks like there is indeed nothing to display...

**Comment by tom-englert** [comment] 2018-08-01 14:47
@wokhan thanks, that narrows it down a bit.

**Comment by tom-englert** [comment] 2018-08-05 10:12
@wokhan can you try again with the latest build from vsix gallery and post the output messages here?

**Comment by bluegrams** [comment] 2018-08-05 21:10
I also got to test it with Snoop now, having the same results as wokhan.

The latest build produces the following output for me if the window fails to display anything (it seems like Newtonsoft.Json is loaded twice, don't know if that is a problem):

> Content resized: 1157 - 621 
Content loaded: 1157 - 621 
VCF: RegionId changed: Shell 
VCF: Update TomsToolbox.Wpf.Composition.ContentControlCompositionBehavior, RegionId=Shell, Role=, ContentControl= 
Content resized: 1173 - 660 
Content resized: 1175 - 691 
Assembly 'DataGridExtensions, Version=1.0.39.0, Culture=neutral, PublicKeyToken=43de855f87de903a' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/DataGridExtensions.DLL
Assembly 'DocumentFormat.OpenXml, Version=2.8.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/DocumentFormat.OpenXml.DLL
Assembly 'Microsoft.Expression.Interactions, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/Microsoft.Expression.Interactions.DLL
Assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/Newtonsoft.Json.DLL
Assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.DLL
Assembly 'ResXManager.Infrastructure, Version=1.23.1160.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/ResXManager.Infrastructure.DLL
Assembly 'ResXManager.Model, Version=1.23.1160.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/ResXManager.Model.dll
Assembly 'ResXManager.Translators, Version=1.23.1160.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/ResXManager.Translators.dll
Assembly 'ResXManager.View, Version=1.23.1160.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/ResXManager.View.dll
Assembly 'ResXManager.VSIX, Version=1.23.1160.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/ResXManager.VSIX.dll
Assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/System.Windows.Interactivity.DLL
Assembly 'TomsToolbox.Core, Version=1.0.71.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/TomsToolbox.Core.DLL
Assembly 'TomsToolbox.Desktop, Version=1.0.71.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/TomsToolbox.Desktop.DLL
Assembly 'TomsToolbox.ObservableCollections, Version=1.0.71.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/TomsToolbox.ObservableCollections.DLL
Assembly 'TomsToolbox.Wpf, Version=1.0.71.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/TomsToolbox.Wpf.DLL
Assembly 'TomsToolbox.Wpf.Styles, Version=1.0.71.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/.../AppData/Local/Microsoft/VisualStudio/15.0_14bf75c9/Extensions/x3etvnjt.qqh/TomsToolbox.Wpf.Styles.DLL
Please read https://github.com/tom-englert/ResXResourceManager/wiki/Fixing-errors before creating an issue.
>
> Exports:
TomsToolbox.Desktop.Composition.ICompositionHost
System.IServiceProvider
System.ComponentModel.Composition.Hosting.ExportProvider
VSPackage
tomenglertde.ResXManager.Infrastructure.ITracer
tomenglertde.ResXManager.Infrastructure.ThemeManager (ContractName="tomenglertde.ResXManager.Infrastructure.ThemeManager")
tomenglertde.ResXManager.Model.CodeReferenceTracker (ContractName="tomenglertde.ResXManager.Model.CodeReferenceTracker")
tomenglertde.ResXManager.Model.PerformanceTracer (ContractName="tomenglertde.ResXManager.Model.PerformanceTracer")
tomenglertde.ResXManager.Model.ResourceManager (ContractName="tomenglertde.ResXManager.Model.ResourceManager")
tomenglertde.ResXManager.Translators.AzureTranslator (ContractName="tomenglertde.ResXManager.Infrastructure.ITranslator")
tomenglertde.ResXManager.Translators.MSTerminologyTranslator (ContractName="tomenglertde.ResXManager.Infrastructure.ITranslator")
tomenglertde.ResXManager.Translators.MyMemoryTranslator (ContractName="tomenglertde.ResXManager.Infrastructure.ITranslator")
tomenglertde.ResXManager.Translators.GoogleTranslator (ContractName="tomenglertde.ResXManager.Infrastructure.ITranslator")
tomenglertde.ResXManager.Translators.TranslatorHost (ContractName="tomenglertde.ResXManager.Translators.TranslatorHost")
tomenglertde.ResXManager.View.DeleteCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.DeleteCommand (ContractName="tomenglertde.ResXManager.View.DeleteCommand")
tomenglertde.ResXManager.View.CutCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.CutCommand (ContractName="tomenglertde.ResXManager.View.CutCommand")
tomenglertde.ResXManager.View.CopyCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.CopyCommand (ContractName="tomenglertde.ResXManager.View.CopyCommand")
tomenglertde.ResXManager.View.PasteCommand (ContractName="tomenglertde.ResXManager.View.PasteCommand")
tomenglertde.ResXManager.View.PasteCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.IsInvariantCommand (ContractName="tomenglertde.ResXManager.View.IsInvariantCommand")
tomenglertde.ResXManager.View.IsInvariantCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.IsItemInvariantCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.IsItemInvariantCommand (ContractName="tomenglertde.ResXManager.View.IsItemInvariantCommand")
tomenglertde.ResXManager.View.ToggleCellSelectionCommand (ContractName="tomenglertde.ResXManager.View.ToggleCellSelectionCommand")
tomenglertde.ResXManager.View.ToggleCellSelectionCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.Visuals.ConfigurationEditorView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.View.Visuals.ConfigurationEditorViewModel (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.Visuals.LanguageConfigurationView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.View.Visuals.InputBox (ContractName="tomenglertde.ResXManager.View.Visuals.InputBox")
tomenglertde.ResXManager.View.Visuals.LanguageConfigurationViewModel (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.Visuals.LanguageSelectionBoxView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.View.Visuals.ResourceView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.View.Visuals.ResourceViewModel (ContractName="tomenglertde.ResXManager.View.Visuals.ResourceViewModel")
tomenglertde.ResXManager.View.Visuals.ResourceViewModel (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.Visuals.ShellView (ContractName="tomenglertde.ResXManager.View.Visuals.ShellView")
tomenglertde.ResXManager.View.Visuals.ShellView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.View.Visuals.ShellViewModel (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.Visuals.ShellViewModel (ContractName="tomenglertde.ResXManager.View.Visuals.ShellViewModel")
tomenglertde.ResXManager.View.Visuals.TranslationsView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.View.Visuals.TranslationsViewModel (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.View.Tools.AddNewKeyCommand (ContractName="tomenglertde.ResXManager.View.Tools.AddNewKeyCommand")
tomenglertde.ResXManager.VSIX.ErrorProvider (ContractName="tomenglertde.ResXManager.VSIX.ErrorProvider")
tomenglertde.ResXManager.VSIX.CodeGeneratorGroupCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.VSIX.CodeGeneratorGroupCommand (ContractName="tomenglertde.ResXManager.VSIX.CodeGeneratorGroupCommand")
tomenglertde.ResXManager.VSIX.ResXFileCodeGeneratorCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.VSIX.ResXFileCodeGeneratorCommand (ContractName="tomenglertde.ResXManager.VSIX.ResXFileCodeGeneratorCommand")
tomenglertde.ResXManager.VSIX.PublicResXFileCodeGeneratorCommand (ContractName="tomenglertde.ResXManager.VSIX.PublicResXFileCodeGeneratorCommand")
tomenglertde.ResXManager.VSIX.PublicResXFileCodeGeneratorCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.VSIX.TextTemplateCodeGeneratorCommand (ContractName="tomenglertde.ResXManager.VSIX.TextTemplateCodeGeneratorCommand")
tomenglertde.ResXManager.VSIX.TextTemplateCodeGeneratorCommand (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.VSIX.DteConfiguration (ContractName="tomenglertde.ResXManager.VSIX.DteConfiguration")
tomenglertde.ResXManager.VSIX.DteConfiguration (ContractName="tomenglertde.ResXManager.Model.Configuration")
tomenglertde.ResXManager.VSIX.DteConfiguration (ContractName="tomenglertde.ResXManager.Model.IConfiguration")
tomenglertde.ResXManager.VSIX.DteSolution (ContractName="tomenglertde.ResXManager.VSIX.DteSolution")
tomenglertde.ResXManager.VSIX.DteSourceFilesProvider (ContractName="tomenglertde.ResXManager.Model.ISourceFilesProvider")
tomenglertde.ResXManager.VSIX.Refactorings (ContractName="tomenglertde.ResXManager.VSIX.IRefactorings")
tomenglertde.ResXManager.VSIX.ThemeResourceProvider (ContractName="TomsToolbox.Wpf.Styles.IThemeResourceProvider")
tomenglertde.ResXManager.VSIX.Visuals.ShowErrorsConfigurationView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.VSIX.Visuals.ShowErrorsConfigurationViewModel (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.VSIX.Visuals.CodeGeneratorView (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.VSIX.Visuals.MoveToResourceConfigurationView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.VSIX.Visuals.MoveToResourceConfigurationViewModel (ContractName="VisualComposition-86E8D1EF-1322-46B4-905C-115AAD63533D")
tomenglertde.ResXManager.VSIX.Visuals.MoveToResourceView (ContractName="{41cf1dfc-9c56-4e06-b177-703b4a24b0e1}")
tomenglertde.ResXManager.VSIX.Visuals.VsixShellView (ContractName="tomenglertde.ResXManager.VSIX.Visuals.VsixShellView")
tomenglertde.ResXManager.VSIX.Visuals.VsixShellViewModel (ContractName="tomenglertde.ResXManager.VSIX.Visuals.VsixShellViewModel")

**Comment by tom-englert** [comment] 2018-08-06 15:41
@bluegrams Newtonsoft is OK here, it's not involved at all.

The problem is something in `System.Windows.Interactivity`, after adding the behavior, it does not attach it to the control...
```
VCF: RegionId changed: Shell
VCF: Update TomsToolbox.Wpf.Composition.ContentControlCompositionBehavior, RegionId=Shell, Role=, ContentControl=
VCF: Attached TomsToolbox.Wpf.Composition.ContentControlCompositionBehavior to tomenglertde.ResXManager.VSIX.Visuals.VsixShellView
VCF: RegionId changed: ProjectListContextMenu
VCF: Update TomsToolbox.Wpf.Composition.ItemsControlCompositionBehavior, RegionId=ProjectListContextMenu, ItemsControl=
...
```

**Comment by tom-englert** [comment] 2018-08-08 06:43
@bluegrams @wokhan can you try with the latest build from VSIXGallery and post the output?

**Comment by tom-englert** [comment] 2018-08-18 14:57
@bluegrams can you give it another try?

**Comment by wokhan** [comment] 2018-08-18 17:10
Last update is working for me with VS 15.8… Will get back at you if it starts failing again :-)
Thanks

**Comment by wokhan** [comment] 2018-08-19 10:29
Some details:
- when the extension is docked on a side (not as a document), i.e. always visible, it doesn't get blank whatever I tried.
- if docked as a document it becomes blank _only_ when switching back from a XAML editor page.
- if docked on a side and then docked back as a document while a XAML editor has been opened in between, it also appears blank.

Definitely looks like a conflict with the XAML editor...

**Comment by db71** [comment] 2018-08-20 18:13
I also have the issue with Visual Studio 2017 Preview in my case. @wokhan is right, when I have no XAML-editor open then ResXManager is working fine, but once I switched to the XAML-editor then ResXManager goes blank. Docked or not.

**Comment by tom-englert** [comment] 2018-08-21 06:25
@wokhan @db71 I assume you are talking about the UWP-XAML editor, right?

**Comment by db71** [comment] 2018-08-21 07:00
Yes, the UWP-XAML editor in Visual Studio.

**Comment by tom-englert** [comment] 2018-08-21 12:28
Finally managed to reproduce this, and even find the root cause!
The UWP-XAML editor switches the **whole** application into design mode, so any WPF control will assume it's running in the designer!
I will raise a bug for Visual Studio, since there is nothing much I can do about this.

**Comment by tom-englert** [comment] 2018-08-23 13:25
Yes, that will affect anyone relying on that property being set correctly! I've already raised a bug at Microsoft. 
However maybe I have found a temporary workaround, can you try the lastest build?

**Comment by db71** [comment] 2018-08-23 14:03
I just tried the latest build. It seem to be working fine now. No more blank screens. Thanks!

Great extension!

Feature request:

It would be nice that when I rename a key, that the key name everywhere in the code also changes. Just like renaming a definition, where VS gives an option to rename all references too.

**Comment by tom-englert** [comment] 2018-08-25 12:29
@db71 pleas create a new issue for the feature request

**Comment by tom-englert** [comment] 2018-08-31 18:02
Added workaround in 1.24 until this gets fixed in Visual Studio by Microsoft.

**Closed by tom-englert** 2018-08-31 18:02 UTC

**Comment by wokhan** [comment] 2018-09-02 17:17
Thank you for everything Tom!!! Now works for me as well.
