### ISSUE TITLE
Please make a version for VS for MAC :)

### ISSUE THREAD

**Issue by Stoffe** [tom-englert/ResXResourceManager#164] opened 2018-08-27 09:59 UTC
Missing this so much on my Visual Studio in my MAC when developing Xamarin apps...
Please look into and consider porting this to an MAC extension too...

**Comment by tom-englert** [comment] 2018-08-27 10:09
Duplicate of #53 
You would have to rewrite the complete UI, which is far the biggest part of the project. 
I won't be capable to do this. 
However maybe some day some one will grab it?

**Closed by tom-englert** 2018-08-27 10:09 UTC
