### ISSUE TITLE
Option Request: Mark identical translations

### ISSUE THREAD

**Issue by Hefaistos68** [tom-englert/ResXResourceManager#269] opened 2019-12-10 09:06 UTC
I have seen many cases (in my inherited projects) where some keys are no translated but copied from one language to another. Would be nice to be able to see those as marked duplicates.
As in this screen shot, the last text in CZ and EN are identical, someone copied EN to CZ without translating.

![resx option](https://user-images.githubusercontent.com/8855055/70514777-2286ec00-1b2c-11ea-9f47-ae32884f6ed4.jpg)

**Comment by tom-englert** [comment] 2019-12-10 12:58
Duplicate of #168

**Closed by tom-englert** 2019-12-10 12:58 UTC
