### ISSUE TITLE
Punctuation warnings are too strict for Spanish

### ISSUE THREAD

**Issue by zhofre** [tom-englert/ResXResourceManager#301] opened 2020-03-02 13:37 UTC
I really like the whitespace and punctuation consistency checks.

However, in Spanish questions and exclamations also get an inverse punctuation mark at the beginning.

Source: https://en.wikipedia.org/wiki/Inverted_question_and_exclamation_marks

Example:
* Are you sure you want to restore the factory database?
* ¿Está seguro que desea restaurar la base de datos de fábrica?

This leads to the warning: **The punctuation at the start of the messages doesn't match up. No punctuation was expected at the start of the message.**

I wouldn't go as far as to say that the inverted has to be there at the start (as there are sentences that have the inverted punctuation halfway in the sentence), but a way to switch of the leading punctuation check for these symbols would be nice.

**Comment by tom-englert** [comment] 2020-03-02 14:19
Duplicate of #283

**Closed by tom-englert** 2020-03-02 14:19 UTC
