### ISSUE TITLE
v 1.39 cannot find 'TomsToolbox.Wpf.Composition.Mef

### ISSUE THREAD

**Issue by CADbloke** [tom-englert/ResXResourceManager#304] opened 2020-03-09 23:21 UTC
VS 16.4.5 (VS 2019) .NET 4.8.03761
from the Visual Studio Activity log...

CreateInstance failed for package [VsPackage]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'TomsToolbox.Wpf.Composition.Mef, Version=2.0.0.4, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' or one of its dependencies. The system cannot find the file specified. at ResXManager.VSIX.VsPackage..ctor() --- End of inner exception stack trace --- at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) at System.Activator.CreateInstance(Type type, Boolean nonPublic) at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark) at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo) at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.IO.FileNotFoundException: Could not load file or assembly 'TomsToolbox.Wpf.Composition.Mef, Version=2.0.0.4, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' or one of its dependencies. The system cannot find the file specified. File name: 'TomsToolbox.Wpf.Composition.Mef, Version=2.0.0.4, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' at ResXManager.VSIX.VsPackage..ctor() WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by tom-englert** [comment] 2020-03-11 09:13
Duplicate of #282

**Closed by tom-englert** 2020-03-11 09:13 UTC
Labels: duplicate
