### ISSUE TITLE
Crash While opening VS 2017 ...

### ISSUE THREAD

**Issue by AhmedRabeeMoahmed** [tom-englert/ResXResourceManager#119] opened 2018-04-18 11:34 UTC
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'EntityFilter' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55
Assembly location: C:\Users\ahmed\AppData\Local\Microsoft\VisualStudio\15.0_67a51e16\Extensions\zs3msmn5.qcz
Version: 1.15.1006.0
.NET Framework Version: 461310 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

**Comment by tom-englert** [comment] 2018-04-18 12:49
Duplicate of #117

**Closed by tom-englert** 2018-04-18 12:49 UTC
Labels: duplicate

**Comment by tom-englert** [comment] 2018-04-18 17:03
Just released 1.16, can you try this?

**Comment by AhmedRabeeMoahmed** [comment] 2018-04-22 06:12
It is working fine now, thank you.
