### ISSUE TITLE
Icon overlay on tool bar

### ISSUE THREAD

**Issue by digocesar** [tom-englert/ResXResourceManager#146] opened 2018-06-25 17:43 UTC
My ResxManager is showing the button of Snapshot over the Excel button.
I'm using Visual Studio 2013.
![image](https://user-images.githubusercontent.com/17618149/41866306-1eca207c-7886-11e8-9177-f918071c9681.png)

**Comment by tom-englert** [comment] 2018-06-28 14:58
I think this was a problem with the styles of VS2013. Maybe you should try an upgrade?

**Comment by Charles-Isaac** [comment] 2018-08-16 13:39
The bug is still present on VS2017

**Comment by Charles-Isaac** [comment] 2018-08-16 19:39
It seems to be intermittent...
![image](https://user-images.githubusercontent.com/15947340/44230879-681aeb00-a16a-11e8-8b94-85a00d771fc9.png)

**Comment by tom-englert** [comment] 2018-08-17 10:26
It's just plain XAML, so I have no control over this: 
```xml
<StackPanel Orientation="Horizontal" Background="Transparent">
  <ContentPresenter Content="{Binding Header, RelativeSource={RelativeSource FindAncestor, AncestorType=MenuItem}}" />
  <Decorator Width="2" />
  <Path x:Name="Path" Data="M 0 0 L 3.5 4 L 7 0 Z" Fill="{DynamicResource {x:Static SystemColors.ControlTextBrushKey}}" VerticalAlignment="Center" />
</StackPanel>
```
Maybe some other extension is overwriting the global menu item style?

**Comment by tom-englert** [comment] 2018-09-08 14:59
Can someone provide instructions how to reproduce this? 
Else I will close this as not reproducible.

**Comment by Charles-Isaac** [comment] 2018-09-10 14:26
It happens often but it's also pretty hard to reproduce.  I'm working on finding what allows to reproduce it every times.

**Comment by mkaring** [comment] 2019-11-11 10:30
I found a relatively easy way to reproduce the issue.
Open the manager up, decrease the width of the window to the point where the two problematic buttons are not visible anymore. Close the manger (and restart Visual Studio, if you try it in VS). Open the manager up again. It stored the last size and will open with the reduced with. If you increase the width of the window now, you the images of both buttons missing. If you hover over the buttons, the images appear but aren't layouted correctly. It looks like in the screenshots above.

It looks like the images aren't resolved in case they are not displayed and once they are displayed the layout isn't fixed.

Testing this works both in visual studio and in the standalone version. But it works easiest in the standalone version, because you just have to restart the manager and not the entire visual studio.

**Closed** 2019-11-29 16:34 UTC
