### ISSUE TITLE
NULL Exception at the Start from the ResxManager

### ISSUE THREAD

**Issue by ChristophSeelbach** [tom-englert/ResXResourceManager#90] opened 2018-03-05 07:13 UTC
Fehler: System.Windows.Markup.XamlParseException: Die Sammlungseigenschaft "Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger"."Actions" ist NULL. ---> System.Xaml.XamlObjectWriterException: Die Sammlungseigenschaft "Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger"."Actions" ist NULL.
   bei System.Xaml.XamlObjectWriter.WriteGetObject()
   bei System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   bei System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:Zeile 1.
   bei tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:Zeile 55.
Installationsverzeichnis: C:\Users\chris\AppData\Local\Microsoft\VisualStudio\15.0_5199366a\Extensions\2yhsdj5o.gru
Version: 1.11.893.0
VS: 15.5.7

**Comment by tom-englert** [comment] 2018-03-06 10:14
Duplicate of #72, please follow instructions there

**Closed by tom-englert** 2018-03-06 10:14 UTC
Labels: duplicate
