### ISSUE TITLE
VS 2017 Pro (version 15.6.1) ResXManager 1.12.976 caused 705 seconds of unresponsiveness while building solution

### ISSUE THREAD

**Issue by kristofhoedt** [tom-englert/ResXResourceManager#100] opened 2018-03-13 10:48 UTC
I'm having troubles when building my solutions. The new version of ResXResourceManager caused 705 seconds of unresponsiveness when I tried to rebuild my solution.

![capture_resxresourcemanager](https://user-images.githubusercontent.com/37331892/37337306-20814fae-26b4-11e8-9983-489dd700b526.PNG)

**Comment by tom-englert** [comment] 2018-03-13 11:00
Duplicate of #97

**Closed by tom-englert** 2018-03-13 11:00 UTC
Labels: duplicate
