### ISSUE TITLE
ResX Manager does not start after update to new version

### ISSUE THREAD

**Issue by hkoestin** [tom-englert/ResXResourceManager#121] opened 2018-04-18 13:31 UTC
Hey there,

since VS did auto update the extension to version 1.15.1006.0 recently, I cannot launch the extension anymore.

I get the following errors.

Maybe somebody can help?

Cheers,
Harald

```
Error: Loader errors at start:
Assembly: Microsoft.Expression.Interactions.dll => GenericArguments[0], 'System.Object', on 'System.Windows.Interactivity.TargetedTriggerAction`1[T]' violates the constraint of type parameter 'T'.: 
GenericArguments[0], 'System.Object', on 'System.Windows.Interactivity.TargetedTriggerAction`1[T]' violates the constraint of type parameter 'T'.: 
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 40
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.TriggerCollection' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Windows.Interactivity.PreviewInvokeEventArgs' from assembly 'System.Windows.Interactivity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Expression.Interactivity.Core.PropertyChangedTrigger.OnAttached()
   at System.Windows.Interactivity.TriggerBase.Attach(DependencyObject dependencyObject)
   at System.Windows.Interactivity.TriggerCollection.ItemAdded(TriggerBase item)
   at System.Windows.Interactivity.AttachableCollection`1.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Int32 oldIndex, T oldValue, Int32 newIndex, T newValue)
   at System.Windows.FreezableCollection`1.AddHelper(T value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.ResourceView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.ResourceView..ctor(ICompositionHost compositionHost) in C:\Agent\_work\9\s\ResXManager.View\Visuals\ResourceView.xaml.cs:line 55
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.View.Visuals.TranslationsView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.View\Visuals\TranslationsView.xaml:line 1
   at tomenglertde.ResXManager.View.Visuals.TranslationsView..ctor(ExportProvider exportProvider) in C:\Agent\_work\9\s\ResXManager.View\Visuals\TranslationsView.xaml.cs:line 33
Assembly location: C:\Users\dev12\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\kghxywp0.imj
Version: 1.15.1006.0
.NET Framework Version: 461308 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
```

**Comment by hkoestin** [comment] 2018-04-18 13:35
Maybe related to #72 and #90

**Comment by tom-englert** [comment] 2018-04-18 13:35
Duplicate of #117 - try latest version from vsixgallery

**Closed by tom-englert** 2018-04-18 13:35 UTC
Labels: duplicate

**Comment by hkoestin** [comment] 2018-04-18 13:39
I have installed the latest version 1.15.1006.
But I am running VS 2015, not 2017.

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02556

Running it as stand-alone now helps.

**Comment by hkoestin** [comment] 2018-04-18 13:44
Downgraded to Version: 1.13.988.0 again, which works for my configuration.

**Comment by tom-englert** [comment] 2018-04-18 17:03
Just released 1.16, can you try this?

**Comment by hkoestin** [comment] 2018-04-19 06:14
I did give it a try now.
Does still not work. See below.

```
Found assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' already loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.DLL.
Found assembly 'JetBrains.Annotations, Version=10.1.5.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' already loaded from file:///C:/Users/dev12/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/JetBrains.Annotations.DLL.
Loaded assembly 'DataGridExtensions, Version=1.0.37.0, Culture=neutral, PublicKeyToken=43de855f87de903a' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/DataGridExtensions.dll.
Loaded assembly 'JetBrains.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/JetBrains.Annotations.dll.
Loaded assembly 'Microsoft.Expression.Interactions, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/Microsoft.Expression.Interactions.dll.
Loaded assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/Newtonsoft.Json.dll.
Loaded assembly 'ResXManager.Infrastructure, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Infrastructure.DLL.
Loaded assembly 'ResXManager.Model, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Model.dll.
Loaded assembly 'ResXManager.Translators, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Translators.dll.
Loaded assembly 'ResXManager.View, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.View.dll.
Loaded assembly 'ResXManager.VSIX, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.VSIX.dll.
Loaded assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/System.Windows.Interactivity.DLL.
Loaded assembly 'TomsToolbox.Core, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Core.DLL.
Loaded assembly 'TomsToolbox.Desktop, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Desktop.DLL.
Loaded assembly 'TomsToolbox.ObservableCollections, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.ObservableCollections.dll.
Loaded assembly 'TomsToolbox.Wpf, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Wpf.DLL.
Loaded assembly 'TomsToolbox.Wpf.Styles, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Wpf.Styles.DLL.
ResX Resource Manager loaded.
Home: https://github.com/tom-englert/ResXResourceManager
Report issues: https://github.com/tom-englert/ResXResourceManager/issues
Support the project by adding a short review: https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details
Assembly location: C:\Users\dev12\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\vw0pj0dx.hse
Version: 1.16.1044.0
.NET Framework Version: 461308 (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager, VsixShellViewModel viewModel) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 45
Assembly 'DataGridExtensions, Version=1.0.37.0, Culture=neutral, PublicKeyToken=43de855f87de903a' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/DataGridExtensions.dll
Assembly 'JetBrains.Annotations, Version=10.1.5.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' loaded from file:///C:/Users/dev12/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/JetBrains.Annotations.DLL
Assembly 'JetBrains.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/JetBrains.Annotations.dll
Assembly 'Microsoft.Expression.Interactions, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/Microsoft.Expression.Interactions.dll
Assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/Newtonsoft.Json.dll
Assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.DLL
Assembly 'ResXManager.Infrastructure, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Infrastructure.DLL
Assembly 'ResXManager.Model, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Model.dll
Assembly 'ResXManager.Translators, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Translators.dll
Assembly 'ResXManager.View, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.View.dll
Assembly 'ResXManager.VSIX, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.VSIX.dll
Assembly 'System.Windows.Interactivity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Users/dev12/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/System.Windows.Interactivity.dll
Assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/System.Windows.Interactivity.DLL
Assembly 'TomsToolbox.Core, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Core.DLL
Assembly 'TomsToolbox.Desktop, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Desktop.DLL
Assembly 'TomsToolbox.ObservableCollections, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.ObservableCollections.dll
Assembly 'TomsToolbox.Wpf, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Wpf.DLL
Assembly 'TomsToolbox.Wpf.Styles, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Wpf.Styles.DLL
Error: System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Interactivity.BehaviorCollection' threw an exception. ---> System.ArgumentException: Cannot add instance of type 'CommandRoutingBehavior' to a collection of type 'BehaviorCollection'. Only items of type 'T' are allowed.
   at System.Windows.FreezableCollection`1.Cast(Object value)
   at System.Windows.FreezableCollection`1.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView.InitializeComponent() in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml:line 1
   at tomenglertde.ResXManager.VSIX.Visuals.VsixShellView..ctor(ExportProvider exportProvider, ThemeManager themeManager, VsixShellViewModel viewModel) in C:\Agent\_work\9\s\ResXManager.VSIX\Visuals\VsixShellView.xaml.cs:line 45
Assembly 'DataGridExtensions, Version=1.0.37.0, Culture=neutral, PublicKeyToken=43de855f87de903a' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/DataGridExtensions.dll
Assembly 'JetBrains.Annotations, Version=10.1.5.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' loaded from file:///C:/Users/dev12/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/JetBrains.Annotations.DLL
Assembly 'JetBrains.Annotations, Version=11.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/JetBrains.Annotations.dll
Assembly 'Microsoft.Expression.Interactions, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/Microsoft.Expression.Interactions.dll
Assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/Newtonsoft.Json.dll
Assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' loaded from file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/Newtonsoft.Json.DLL
Assembly 'ResXManager.Infrastructure, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Infrastructure.DLL
Assembly 'ResXManager.Model, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Model.dll
Assembly 'ResXManager.Translators, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.Translators.dll
Assembly 'ResXManager.View, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.View.dll
Assembly 'ResXManager.VSIX, Version=1.16.1044.0, Culture=neutral, PublicKeyToken=695a75ddb69d5a4b' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/ResXManager.VSIX.dll
Assembly 'System.Windows.Interactivity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Users/dev12/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/System.Windows.Interactivity.dll
Assembly 'System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/System.Windows.Interactivity.DLL
Assembly 'TomsToolbox.Core, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Core.DLL
Assembly 'TomsToolbox.Desktop, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Desktop.DLL
Assembly 'TomsToolbox.ObservableCollections, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.ObservableCollections.dll
Assembly 'TomsToolbox.Wpf, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Wpf.DLL
Assembly 'TomsToolbox.Wpf.Styles, Version=1.0.64.0, Culture=neutral, PublicKeyToken=60b39f873a8e3fc2' loaded from file:///C:/Users/dev12/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/vw0pj0dx.hse/TomsToolbox.Wpf.Styles.DLL
```

**Comment by hkoestin** [comment] 2018-04-19 06:45
Well, but I can't update to a new version of R# now, as I do not have a lic for the new versions.

**Comment by tom-englert** [comment] 2018-04-19 06:52
So you have to stay with ResXManger 1.13, too
