### ISSUE TITLE
Sorting problems

### ISSUE THREAD

**Issue by GieltjE** [tom-englert/ResXResourceManager#39] opened 2017-09-14 14:20 UTC
Using the 1.5 release with Visual Studio 15.3.4 within a C# 4.7 project the "When saving a RESX file, sort the XML data nodes by the key" Sort using: "OrdinalIgnoreCase" doesn't sort the RESX files after adding a new key.

Also "Sort all files now" crashes visual studio.

Another bug, pressing ctrl+s doesn't save any changes, clicking the save-all button does.

**Comment by tom-englert** [comment] 2017-09-14 17:48
Please try the latest build from http://vsixgallery.com/

ctr+s is handled by Visual Studio and saves the active document (you can see the active document in the File-Save menu) - but ResXManager is not a "document"

**Comment by GieltjE** [comment] 2017-09-15 08:57
That most definately fixes the sort all button 👍 

However when I use the + button to add a new key to some resource files the key is still placed at the end of all files.

**Comment by GieltjE** [comment] 2017-09-18 08:42
The last bug still isn't fixed, or did I miss something?

**Comment by tom-englert** [comment] 2017-09-18 09:05
If you talk about "However when I use the + button to add a new key to some resource files the key is still placed at the end of all files.": I could not reproduce this, if sorting is checked in the options, it works fine.
Do you do anything special?

**Comment by GieltjE** [comment] 2017-09-18 09:09
Nothing really special, I select the group of translations the new key should be added to, press the + button, enter the values and press the save-all button.

If there is a way to help debug this please let me know as this affects all our developper machines (All VS21017 community edition with either Win10 or Win8 both X64)

**Comment by tom-englert** [comment] 2017-09-24 18:06
Yes, maybe you can try to debug this, you should set a break-point around here:
https://github.com/tom-englert/ResXResourceManager/blob/master/ResXManager.Model/ResourceLanguage.cs#L272

**Comment by tom-englert** [comment] 2017-09-24 18:08
@GieltjE Where do you click save - in the Visual Studio toolbar, or in the ResXManager toolbar?

**Comment by GieltjE** [comment] 2017-09-24 19:25
On the visual studio toolbar, debugging would have to wait a few days (but it will be done)

**Comment by GieltjE** [comment] 2017-09-25 09:39
After trying around a bit, these are the two main things I noticed:

1: Saving new/updated items from the visual studio save-all button adds to the bottom or updates the current location
2: Saving new/updated items from the built in save button properly sorts the items, but leaves untouched elements within the same item/translation (e.g. untouched languages) in the old position.

**Comment by tom-englert** [comment] 2017-09-25 14:44
I think I got the problem - saving via the VS toolbar does not trigger the sorting.

Until this is fixed you can use the save button in the ResXManager toolbar, or check "Save files immediately upon change". 

However as the function implies, sorting only happens when saving, so unchanged files won't be saved. You can use the "Sort all files now" in the configuration tab to achieve this.

**Comment by GieltjE** [comment] 2017-09-25 15:14
Thanks for your help, looking forward to the new version (manually clicking the "Sort all files now" should suffice for the time being).

**Closed** 2017-09-28 15:08 UTC
