### ISSUE TITLE
Error when trying Azure translate

### ISSUE THREAD

**Issue by shahzadgodil2** [tom-englert/ResXResourceManager#216] opened 2019-04-11 14:49 UTC
I am getting this error when trying to use Azure translate

Your application screenshot
https://www.awesomescreenshot.com/image/3968474/c2b0d8fa21b3f512b95a16383d392665

Azure keys screenshot
https://www.awesomescreenshot.com/image/3968478/39d84e80d03232ae5552e3633539abc1

Please help

**Comment by tom-englert** [comment] 2019-04-12 09:20
This is because of #205 - maybe you want to provide a PR for this?

**Comment by tom-englert** [comment] 2019-04-12 09:20
Duplicate of #205

**Closed by tom-englert** 2019-04-12 09:20 UTC
Labels: duplicate
