### ISSUE TITLE
Asp.Net Core

### ISSUE THREAD

**Issue by werddomain** [tom-englert/ResXResourceManager#14] opened 2017-05-27 20:47 UTC
I have a asp.net core with resources in an other project.
When i open the Resx Manager the first time, visual studio stop responding.

The next time i have open it, it worked.
Just want to let you know ;-)

**Comment by werddomain** [comment] 2017-05-27 21:00
Same thing happen when you translate, aply all and a resource for a language need to be created

**Comment by tom-englert** [comment] 2017-06-05 09:51
Maybe that's due to the way how the solution enumerates all items. 
In asp.net projects all files in the (sub)folders are considered as item of the project, which can be many and may take a long time to cache.

If VS stops responding, does it utilize processor and disk time, or is it idle?

**Comment by tom-englert** [comment] 2017-06-13 15:19
@werddomain is this still reproducible?

**Comment by werddomain** [comment] 2017-06-14 04:31
I did not try to reproduce it. But vs stopped responding many time after i have posted this issue.
The cpu dont seem to be buzzy, sice other program work correctly and fluidly. 
If it can help you, i use 3 project with .net standard and one asp.net core project. 
Ressources are in 2 project.
when the error ocur, it has stoped in the middle of the operation. I can redo the task 1 or 2 time and i can be able to terminate the task.

**Comment by tom-englert** [comment] 2017-06-17 09:39
I could not reproduce this. I added an asp.net core project to an existing solution, and it worked fine.
Can you post a solution where this is reproducible?

**Comment by tom-englert** [comment] 2017-08-14 11:56
Closed as not reproducible, and no sample has been provided.

**Closed by tom-englert** 2017-08-14 11:56 UTC
