### ISSUE TITLE
Resource usage not detected

### ISSUE THREAD

**Issue by MikeCharlesworth** [tom-englert/ResXResourceManager#255] opened 2019-11-08 09:19 UTC
The "Detect Code REferences" feature has saved me a lot of time clearing iout unused resources. However It did mark a couple of resources as being unused which were in use.

The code was similar to 

        public string Title => MyProject.Resources.Resources
                                             .TheProjectTitle;

When I removed the linebreak it found the refereence

**Comment by tom-englert** [comment] 2019-11-10 10:34
Duplicate of #80. So far no one succeeded to fix this.

**Closed by tom-englert** 2019-11-10 10:34 UTC
Labels: duplicate
